config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root	'users#home'

  get	'/add_employee',	to: 'employees#new'
  post	'/add_employee',	to: 'employees#create'

  get	'/add_user',		to: 'users#new'
  post	'/add_user',		to: 'users#create'

  get	'/add_department',	to: 'departments#new'
  post	'/add_department',	to: 'departments#create'

  get	'/add_jobtitle',	to: 'job_titles#new'
  post	'/add_jobtitle',	to: 'job_titles#create'

  # resources :users
  # resources :department
  # resources :job_title
end

app/models/address.rb
class Address
  include Mongoid::Document
  field :line, type: String
  field :city, type: String
  field :state, type: String
  field :zip, type: Integer
  field :country, type: String

  embedded_in :employee

  validates :line, :city, :state, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department
  include Mongoid::Document
  field :name, type: String

  # has_many :employees, autosave: true

  validates :name, :presence => true
end

app/models/employee.rb
class Employee
  include Mongoid::Document
  field :first_name, type: String
  field :middle_name, type: String
  field :last_name, type: String
  field :birthday, type: String
  field :department_id, type: BSON::ObjectId

  has_and_belongs_to_many :job_titles
  embeds_many :addresses

  validates :first_name, length: { minimum: 2, :message => "What" }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :last_name, length: { minimum: 5, :message => "What" }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
end

app/models/job_title.rb
class JobTitle
  include Mongoid::Document
  field :name, type: String
  field :start_date, type: Date
  field :end_date, type: Date

  has_and_belongs_to_many :employees, inverse_of: nil

  validates :name, :presence => true
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :username, type: String
  field :password_digest, type: String
  field :employee_id, type: BSON::ObjectId
  has_secure_password

  validates :password_digest, length: { minimum: 6, :message => "What" }

  validates :username, :employee_id, :presence => true
  validates :employee_id, :username, :uniqueness => true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index
    @employees = Employee.all
  end

  def new
    @address = Address.new
  end

  def create
    @employee = Employee.find(params[:employee_id])
    @address = @employee.address.new(address_params)

    if @address.save
      redirect_to addresses_path, notice: "The address has been added!" and return
    end
    render 'new'
  end

  def edit
  end

  def update
    if @address.update_attributes(address_params)
      redirect_to addresses_path, notice: 'The address has been updated!' and return
    end
    render 'edit'
  end

  def destroy
    @address.destroy
    redirect_to addresses_path, notice: 'The address has been deleted!' and return
  end

  private
    def address_params
      params.require(:address).permit(:line, :city, :state, :zip, :country, :employee)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
	before_action :set_department, only: [:edit, :update, :destroy]

  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path, notice: "The department has been created!" and return
    end
    render 'new'
  end

  def edit
  end

  def update
    if @department.update_attributes(department_params)
      redirect_to departments_path, notice: 'The department has been updated!' and return
    end
    render 'edit'
  end

  def destroy
    @department.destroy
    redirect_to departments_path, notice: 'The department has been deleted!' and return
  end

  private
    def set_department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :set_employee, only: [:edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path, notice: "The employee has been created!" and return
    end
    render 'new'
  end

  def edit
  end

  def update
    if @employee.update_attributes(employee_params)
      redirect_to employees_path, notice: 'The employee has been updated!' and return
    end
    render 'edit'
  end

  def destroy
    @employee.destroy
    redirect_to employees_path, notice: 'The employee  has been deleted!' and return
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :middle_name, :last_name, :birthday, :department_id)
    end
end

app/controllers/job_titles_controller.rb
class JobTitlesController < ApplicationController
	before_action :set_job_title, only: [:edit, :update, :destroy]

	def index
		@job_titles = JobTitle.all
	end

	def new
		@job_title = JobTitle.new
	end

	def create
		@job_title = JobTitle.new(job_title_params)

		if @job_title.save
		  redirect_to job_titles_path, notice: "The Job Title has been created!" and return
		end
		render 'new'
	end

	def edit
	end

	def update
		if @job_title.update_attributes(job_title_params)
		  redirect_to job_titles_path, notice: 'Job Title has been updated!' and return
		end
		render 'edit'
	end

	def destroy
		@job_title.destroy
		redirect_to job_titles_path, notice: 'Job Title has been deleted!' and return
	end

	private
	def set_job_title
		@job_title = JobTitle.find(params[:id])
	end

	def job_title_params
		params.require(:job_title).permit(:name)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "The user has been created!" and return
    end
    render 'new'
  end

  def edit
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to users_path, notice: 'The user has been updated!' and return
    end

    render 'edit'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path, notice: 'The user has been deleted!' and return
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :employee_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address, :url => { :action => yield(:kind), :controller => "addresses" } ) do |f| %>

<%= f.label :employee %>
<%= f.collection_select :employee, Employee.all, :id, :first_name, {}, :class=>'form-control' %>

<%= f.label :line, 'Address Line' %>
<%= f.text_field :line, class: 'form-control' %>

<%= f.label :city, 'City' %>
<%= f.text_field :city, class: 'form-control' %>

<%= f.label :state, 'State' %>
<%= f.text_field :state, class: 'form-control' %>

<%= f.label :country, 'Country' %>
<%= f.text_field :country, class: 'form-control' %>

<%= f.submit yield(:button), class: "btn btn-primary" %>
<% end %>

app/views/addresses/create.html.erb
<h1>Address#create</h1>
<p>Find me in app/views/address/create.html.erb</p>

app/views/addresses/destroy.html.erb
<h1>Address#destroy</h1>
<p>Find me in app/views/address/destroy.html.erb</p>

app/views/addresses/edit.html.erb
<% provide(:title, "Edit Address") %>
<% provide(:button, "Update") %>
<% provide(:button, "update") %>
<h1>Address</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/addresses/index.html.erb
<% provide(:title, "Employee Address") %>
<h1>Address</h1>
	<div class="well">
    <% if @employees.size == 0 %>
      <%= link_to "New Employee", new_employee_path, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Add Address", new_address_path, class: "btn btn-primary" %>
    <% end %> 
  </div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Employee</th>
      <th>Line</th>
      <th>City</th>
      <th>State</th>
      <th>Zip Code</th>
      <th>Country</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @employees.size == 0 %>
      <tr>
        <td colspan="10">No employees found.</td>
      </tr>
    <% else %>
      <% @employees.each do |employee| %>
        <% if employee.addresses.size > 0 %>
          <% employee.addresses.each do |address| %>
            <tr>
              <td><%= employee.first_name + ' ' + employee.middle_name + ' ' + employee.last_name %></td>
              <td><%= address.line %></td>
              <td><%= address.city %></td>
              <td><%= address.state %></td>
              <td><%= address.zip %></td>
              <td><%= address.country %></td>
              <td>
                <%= link_to "Edit", edit_employee_path(employee), class: "btn btn-default" %>
              </td>
              <td>
                <%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure you wish to delete this employee' }, class: "btn btn-danger"  %></td>
              </td>
            </tr>
          <% end %>
          <tr></tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/addresses/new.html.erb
<% provide(:title, "Add Address") %>
<% provide(:button, "Create") %>
<% provide(:kind, "create") %>
<h1>Address</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/addresses/update.html.erb
<h1>Address#update</h1>
<p>Find me in app/views/address/update.html.erb</p>

app/views/departments/_form.html.erb
<%= form_for(@department, :url => { :action => yield(:kind), :controller => "departments" } ) do |f| %>

<%= f.label :name, 'Name' %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.submit yield(:button), class: "btn btn-primary" %>
<% end %>

app/views/departments/create.html.erb
<h1>Department#create</h1>
<p>Find me in app/views/department/create.html.erb</p>

app/views/departments/destroy.html.erb
<h1>Department#destroy</h1>
<p>Find me in app/views/department/destroy.html.erb</p>

app/views/departments/edit.html.erb
<% provide(:title, "New Department") %>
<% provide(:button, "Update") %>
<% provide(:kind, "update") %>
<h1>Departments</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/departments/index.html.erb
<% provide(:title, "Department") %>
<h1>Departments</h1>
<div class="well">
  <%= link_to "New Department", new_department_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Department</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @departments.size == 0 %>
      <tr>
        <td colspan="6">No departments found.</td>
      </tr>
    <% else %>
      <% @departments.each do |department| %>
        <tr>
          <td><%= department.name %></td>
          <td>
            <%= link_to "Edit", edit_department_path(department), class: "btn btn-success" %>
          </td>
          <td>
            <%= link_to 'Delete', department, method: :delete, data: { confirm: 'Are you sure you wish to delete this department' }, class: "btn btn-danger"  %></td>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/departments/new.html.erb
<% provide(:title, "New Department") %>
<% provide(:button, "Create") %>
<% provide(:kind, "create") %>
<h1>Departments</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/departments/update.html.erb
<h1>Department#update</h1>
<p>Find me in app/views/department/update.html.erb</p>

app/views/employees/_form.html.erb
<%= form_for(@employee, :url => { :action => yield(:kind), :controller => "employees" } ) do |f| %>

<%= f.label :first_name, 'First Name' %>
<%= f.text_field :first_name, class: 'form-control' %>

<%= f.label :middle_name, 'Middle Name' %>
<%= f.text_field :middle_name, class: 'form-control' %>

<%= f.label :last_name, 'Last Name' %>
<%= f.text_field :last_name, class: 'form-control' %>

<%= f.label :birthday %>
<%= date_field :employee, :birthday, class: 'form-control' %>

<%= f.label :department_id %>
<%= f.collection_select :department_id, Department.all, :id, :name, {}, :class=>'form-control' %>

<%= f.submit yield(:button), class: "btn btn-primary" %>
<% end %>

app/views/employees/create.html.erb
<h1>Employee#create</h1>
<p>Find me in app/views/employee/create.html.erb</p>

app/views/employees/destroy.html.erb
<h1>Employee#destroy</h1>
<p>Find me in app/views/employee/destroy.html.erb</p>

app/views/employees/edit.html.erb
<% provide(:title, "Edit Employee") %>
<% provide(:button, "Update") %>
<% provide(:kind, "update") %>
<h1>Employees</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/employees/index.html.erb
<% provide(:title, "Employee") %>
<h1>Employees</h1>
<div class="well">
  <%= link_to "New Employee", new_employee_path, class: "btn btn-primary" %>
  <% if @employees.size > 0 %>
  <%= link_to "Assign Job Title", '#', class: "btn btn-warning" %>
  <%= link_to "View Addresses", addresses_path, class: "btn btn-info" %>
  <%= link_to "View Users", users_path, class: "btn btn-success" %>
  <% end %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Middle Name</th>
      <th>Last Name</th>
      <th>Birthday</th>
      <th>Department</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @employees.size == 0 %>
      <tr>
        <td colspan="10">No employees found.</td>
      </tr>
    <% else %>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.first_name %></td>
          <td><%= employee.middle_name %></td>
          <td><%= employee.last_name %></td>
          <td><%= employee.birthday %></td>
          <td>
            <% if employee.department_id != nil %>
              <%= Department.find(employee.department_id).name %>
            <% end %>
          </td>
          <td>
            <%= link_to "Edit", edit_employee_path(employee), class: "btn btn-default" %>
          </td>
          <td>
            <%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure you wish to delete this employee' }, class: "btn btn-danger"  %></td>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<% provide(:title, "New Employee") %>
<% provide(:button, "Create") %>
<% provide(:kind, "create") %>
<h1>Employees</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/employees/update.html.erb
<h1>Employee#update</h1>
<p>Find me in app/views/employee/update.html.erb</p>

app/views/job_titles/_form.html.erb
<%= form_for(@job_title, :url => { :action => yield(:kind), :controller => "job_titles" } ) do |f| %>

<%= f.label :name, 'Name' %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.submit yield(:button), class: "btn btn-primary" %>
<% end %>

app/views/job_titles/create.html.erb
<h1>JobTitle#create</h1>
<p>Find me in app/views/job_title/create.html.erb</p>

app/views/job_titles/destroy.html.erb
<h1>JobTitle#destroy</h1>
<p>Find me in app/views/job_title/destroy.html.erb</p>

app/views/job_titles/edit.html.erb
<% provide(:title, "Edit Job Title") %>
<% provide(:button, "Update") %>
<% provide(:kind, "update") %>
<h1>Job Titles</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/job_titles/index.html.erb
<% provide(:title, "Job Titles") %>
<h1>Job Titles</h1>
<div class="well">
  <%= link_to "New Job Title", new_job_title_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Job Title</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @job_titles.size == 0 %>
      <tr>
        <td colspan="6">No job_titles found.</td>
      </tr>
    <% else %>
      <% @job_titles.each do |job_title| %>
        <tr>
          <td><%= job_title.name %></td>
          <td>
            <%= link_to "Edit", edit_job_title_path(job_title), class: "btn btn-success" %>
          </td>
          <td>
            <%= link_to 'Delete', job_title, method: :delete, data: { confirm: 'Are you sure you wish to delete this job title?' }, class: "btn btn-danger"  %></td>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/job_titles/new.html.erb
<% provide(:title, "New Job Title") %>
<% provide(:button, "Create") %>
<% provide(:kind, "create") %>
<h1>Job Titles</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/job_titles/update.html.erb
<h1>JobTitle#update</h1>
<p>Find me in app/views/job_title/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Ruby on Rails and MongoDB
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
    <nav>
    	<ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "Home",   root_path %></li>
      	<li><%= link_to "Employee", employees_path %></li>
      	<li><%= link_to "Job Title", job_titles_path %></li>
        <li><%= link_to "Department", departments_path %></li>
    	</ul>
    </nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1 style="text-align: center;">Welcome to the Employee Record</h1>

  <h2 style="text-align: center;">
    This is the home page for Employee Record
  </h2>

  <%= link_to "Login", '#', class: "btn btn-lg btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, :url => { :action => yield(:kind), :controller => "users" } ) do |f| %>

<%= f.label :username %>
<%= f.text_field :username, class: 'form-control' %>

<%= f.label :password, 'Password' %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, 'Password Confirmation' %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.label :employee_id %>
<%= f.collection_select(:employee_id, Employee.all, :id, :first_name, {}, {:class=>'form-control'}) %>

<%= f.submit yield(:button), class: "btn btn-primary" %>
<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<% provide(:button, "Update") %>
<% provide(:kind, "update") %>
<h1>Users</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<div class="well">
  <%= link_to "New User", new_user_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Employee</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @users.size == 0 %>
      <tr>
        <td colspan="5">No users found.</td>
      </tr>
    <% else %>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.password %></td>
          <% employee = Employee.find(user.employee_id) %>
          <td><%= employee.first_name + ' ' + employee.middle_name + ' ' + employee.last_name %></td>
          <td>
            <%= link_to "Edit", edit_user_path(user), class: "btn btn-success" %>
          </td>
          <td>
            <%= button_to "Delete", user, method: :delete, data: { confirm: 'Are you sure you wish to delete this user?' }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, "New User") %>
<% provide(:button, "Create") %>
<% provide(:kind, "create") %>
<h1>Users</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h2>
        This is the employee profile
      </h2>
    </section>
  </aside>
</div>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>